import { MapPin, Camera, Radio, StopCircle, MessageSquare, AlertCircle, Wrench, MapPin as MapPinIcon, Copy, Settings, Check, Pencil, X, Grid3x3, Maximize2 } from 'lucide-react';
import { LiveVideoFeed } from './LiveVideoFeed';
import { TimelineSeeker } from './TimelineSeeker';
import { GlobalActionsToolbar } from './GlobalActionsToolbar';
import { useState } from 'react';
import { InlineMapView } from './InlineMapView';

interface Alert {
  id: string;
  timestamp: Date;
  title: string;
  description: string;
  riskLevel: 'critical' | 'warning' | 'info';
  videoSnippet?: string;
  acknowledged: boolean;
}

interface InlineMonitoringProps {
  location: {
    lat: number;
    lng: number;
    siteName: string;
  };
  assetName: string;
  alerts: Alert[];
  onRadioOperator: (id: string) => void;
  onVerifyPlan?: () => void;
  onShowMap?: () => void;
  onShowVideo?: () => void;
  onAlert?: () => void;
}

interface TimelineBookmark {
  id: string;
  time: number;
  label?: string;
  note?: string;
  tags?: string[];
}

interface CameraView {
  id: string;
  name: string;
  angle: string;
  active: boolean;
}

export function InlineMonitoring({ 
  location, 
  assetName,
  alerts,
  onRadioOperator,
  onVerifyPlan,
  onShowMap,
  onShowVideo,
  onAlert
}: InlineMonitoringProps) {
  const [isPlaying, setIsPlaying] = useState(true);
  const [currentTime, setCurrentTime] = useState(3847);
  const [duration] = useState(7200);
  const [bookmarks, setBookmarks] = useState<TimelineBookmark[]>([
    { id: '1', time: 600, label: 'Asset arrival at Zone B', tags: ['logistics'] },
    { id: '2', time: 1200, label: 'Equipment startup & calibration', tags: ['operation'] },
    { id: '3', time: 1800, label: 'Initial grading pass - Section A', tags: ['grading'] },
    { id: '4', time: 2400, label: 'Safety check: Proximity sensors active', tags: ['safety'] },
    { id: '5', time: 3000, label: 'Shift handover: Operator A to B', tags: ['personnel'] },
    { id: '6', time: 3600, label: 'Idle state detected: Waiting for material', tags: ['idle'] },
    { id: '7', time: 4200, label: 'Refueling completed (24.2 gal)', tags: ['maintenance'] },
    { id: '8', time: 4800, label: 'Grading resumed - Section B', tags: ['grading'] },
    { id: '9', time: 5400, label: 'Auto-leveling sensor adjusted', tags: ['technical'] },
    { id: '10', time: 6000, label: 'Slope verification check', tags: ['quality'] },
    { id: '11', time: 6600, label: 'Lunch break period started', tags: ['break'] },
    { id: '12', time: 7100, label: 'Maintenance check: Hydraulic pressure stable', tags: ['maintenance'] },
  ]);
  const [showMapHover, setShowMapHover] = useState(false);
  const [selectedCamera, setSelectedCamera] = useState<string>('front');
  const [cameras] = useState<CameraView[]>([
    { id: 'front', name: 'Front Dash-Cam', angle: 'Front 180°', active: true },
    { id: 'rear', name: 'Rear View', angle: 'Rear 120°', active: false },
    { id: 'cabin', name: 'Cabin View', angle: 'Operator', active: false },
    { id: 'side-left', name: 'Left Side', angle: 'Port 90°', active: false },
  ]);
  const [commentText, setCommentText] = useState('');
  const [summaryCopied, setSummaryCopied] = useState(false);
  const [showActivityInput, setShowActivityInput] = useState(false);
  const [activityText, setActivityText] = useState('');
  const [primaryView, setPrimaryView] = useState<'video' | 'map'>('video');

  const handleAddBookmark = (time: number) => {
    const newBookmark: TimelineBookmark = {
      id: `bookmark-${Date.now()}`,
      time,
    };
    setBookmarks([...bookmarks, newBookmark]);
  };

  const handleUpdateBookmark = (id: string, data: Partial<TimelineBookmark>) => {
    setBookmarks(bookmarks.map(b => b.id === id ? { ...b, ...data } : b));
  };

  const handleSendComment = () => {
    if (commentText.trim()) {
      const newBookmark: TimelineBookmark = {
        id: `comment-${Date.now()}`,
        time: currentTime,
        label: commentText,
        tags: ['comment'],
      };
      setBookmarks([...bookmarks, newBookmark]);
      setCommentText('');
    }
  };

  const formatTime = (seconds: number) => {
    const mins = Math.floor(seconds / 60);
    const secs = seconds % 60;
    return `${mins}:${secs.toString().padStart(2, '0')}`;
  };

  const handleCopySummary = async () => {
    const summaryText = `Dozer AI Monitoring Summary - ${assetName}\n\nAsset operating in idle state for 1 hour 4 minutes. No critical safety events detected. Two routine maintenance checks completed. Equipment showed normal operational parameters throughout monitoring period. Operator remained in cabin during entire session.\n\nGenerated by Dozer AI at ${new Date().toLocaleString()}`;
    await navigator.clipboard.writeText(summaryText);
    setSummaryCopied(true);
    setTimeout(() => setSummaryCopied(false), 2000);
  };

  const handleRecordActivity = () => {
    if (activityText.trim()) {
      const newBookmark: TimelineBookmark = {
        id: `activity-${Date.now()}`,
        time: currentTime,
        label: activityText,
        tags: ['activity'],
      };
      setBookmarks([...bookmarks, newBookmark]);
      setActivityText('');
      setShowActivityInput(false);
    }
  };

  return (
    <div className="bg-card rounded-[var(--radius-card)] border-2 border-border overflow-hidden shadow-[var(--elevation-sm)]">
      {/* Module Header */}
      <div className="px-6 py-4 border-b-2 border-border flex items-center justify-between">
        <h3 className="text-foreground flex items-center gap-2">
          <Grid3x3 className="w-5 h-5" />
          AI-Assisted Site Monitoring
        </h3>
        <span className="font-[family-name:var(--font-family)] text-muted-foreground" style={{ fontSize: 'var(--text-sm)' }}>
          Idle Survaillance: {assetName}
        </span>
      </div>

      <div className="flex flex-col">
        {/* Main View Container */}
        <div className="relative h-[500px] bg-[#1a1a1a] overflow-hidden">
          {primaryView === 'video' ? (
            /* Video View */
            <div className="absolute inset-0 flex items-center justify-center">
              <div className="absolute inset-0 bg-gradient-to-br from-[#2a2a2a] via-[#3a3a3a] to-[#1a1a1a]">
                <div className="absolute inset-0 opacity-30" style={{
                  backgroundImage: `radial-gradient(circle at 20% 50%, rgba(80, 80, 80, 0.4) 0%, transparent 50%),
                                   radial-gradient(circle at 80% 30%, rgba(100, 100, 100, 0.3) 0%, transparent 50%),
                                   radial-gradient(circle at 40% 80%, rgba(60, 60, 60, 0.4) 0%, transparent 50%)`
                }}></div>
              </div>
              
              <div className="absolute bottom-1/4 left-1/3 w-48 h-32 bg-[#707070] border-4 border-[#505050] rounded-lg shadow-2xl transform rotate-[-12deg]">
                <div className="absolute inset-2 border-2 border-[#505050]/50"></div>
              </div>

              <div className="absolute top-1/2 left-1/4 w-32 h-40 border-2 border-white/20 rounded-lg">
                <div className="absolute -top-6 left-0 px-2 py-0.5 bg-white/20 text-white rounded text-[10px]">98.2% Person Detected</div>
              </div>

              <div className="absolute top-4 left-4 px-3 py-1 bg-black/60 rounded text-xs text-white backdrop-blur-sm">
                {new Date().toLocaleTimeString()}
              </div>

              <div className="absolute bottom-4 left-4 px-3 py-1 bg-muted-foreground/80 rounded flex items-center gap-2 text-white text-xs">
                <div className="w-1.5 h-1.5 bg-white rounded-full animate-pulse"></div>
                AI Active
              </div>

              {/* Integrated Map Floater */}
              <div 
                className="absolute bottom-3 right-3 w-40 aspect-[4/3] bg-[#b8e5c8] rounded-lg border-2 border-white shadow-2xl overflow-hidden cursor-pointer group/map hover:scale-105 transition-transform duration-300 z-30"
                onClick={() => setPrimaryView('map')}
              >
                <div className="absolute inset-0 bg-[linear-gradient(rgba(0,0,0,0.05)_1px,_transparent_1px),_linear-gradient(90deg,rgba(0,0,0,0.05)_1px,_transparent_1px)] bg-[length:10px_10px]"></div>
                <div className="absolute top-1/2 w-full h-8 bg-black/5 -translate-y-1/2 flex items-center justify-center">
                  <div className="w-full h-px bg-white/20"></div>
                </div>
                <div className="absolute left-1/2 h-full w-8 bg-black/5 -translate-x-1/2 flex items-center justify-center">
                  <div className="h-full w-px bg-white/20"></div>
                </div>
                <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2">
                  <div className="relative bg-white rounded-full p-1 shadow-md border border-black/10">
                    <div className="w-2.5 h-2.5 bg-black rounded-full"></div>
                  </div>
                </div>
                <div className="absolute bottom-1.5 right-1.5 w-7 h-7 bg-white/90 backdrop-blur-sm rounded flex items-center justify-center text-black shadow-lg">
                  <Maximize2 className="w-4 h-4" />
                </div>
                <div className="absolute inset-x-0 bottom-0 py-1 bg-black/60 backdrop-blur-sm transform translate-y-full group-hover/map:translate-y-0 transition-transform duration-300">
                  <p className="text-[10px] text-white text-center font-bold tracking-tight uppercase">Open Site Map</p>
                </div>
              </div>
            </div>
          ) : (
            /* Map View */
            <div className="absolute inset-0 bg-background">
              <div className="h-full w-full">
                <InlineMapView 
                  assetName={assetName} 
                  location={location}
                  className="h-full"
                />
              </div>

              {/* Video Floater */}
              <div 
                className="absolute bottom-3 right-3 w-40 aspect-[4/3] bg-[#1a1a1a] rounded-lg border-2 border-white shadow-2xl overflow-hidden cursor-pointer group/video hover:scale-105 transition-transform duration-300 z-30"
                onClick={() => setPrimaryView('video')}
              >
                <div className="absolute inset-0 bg-gradient-to-br from-[#2a2a2a] via-[#3a3a3a] to-[#1a1a1a] opacity-80"></div>
                <div className="absolute inset-0 flex items-center justify-center">
                  <Camera className="w-8 h-8 text-white/40" />
                </div>
                <div className="absolute bottom-1.5 right-1.5 w-7 h-7 bg-white/90 backdrop-blur-sm rounded flex items-center justify-center text-black shadow-lg">
                  <Maximize2 className="w-4 h-4" />
                </div>
                <div className="absolute inset-x-0 bottom-0 py-1 bg-black/60 backdrop-blur-sm transform translate-y-full group-hover/video:translate-y-0 transition-transform duration-300">
                  <p className="text-[10px] text-white text-center font-bold tracking-tight uppercase">Open Video Feed</p>
                </div>
              </div>
            </div>
          )}

          {/* Contextual Toolbar - Overlays both views */}
          <GlobalActionsToolbar 
            variant="video"
            onVerifyPlan={onVerifyPlan}
            onShowMap={onShowMap}
            onShowVideo={onShowVideo}
            onAlert={onAlert}
          />

          {/* Floating Camera Selector - Top Right */}
          <div className="absolute top-4 right-4">
            <div className="bg-black/60 backdrop-blur-md rounded-lg p-2 border border-white/10 w-[180px]">
              <div className="flex items-center gap-2 px-1 mb-2">
                <Camera className="w-3.5 h-3.5 text-white" />
                <span className="text-white text-[11px] font-medium">CAMERAS</span>
              </div>
              <div className="space-y-1">
                {cameras.map((camera) => (
                  <button
                    key={camera.id}
                    onClick={() => setSelectedCamera(camera.id)}
                    className={`w-full px-2 py-1.5 rounded transition-colors text-left ${
                      selectedCamera === camera.id
                        ? 'bg-white text-foreground'
                        : 'text-white/70 hover:bg-white/10'
                    }`}
                  >
                    <div className="text-[11px] font-medium leading-none">{camera.name}</div>
                  </button>
                ))}
              </div>
            </div>
          </div>
        </div>


        {/* Timeline Seeker */}
        <div className="px-6 py-4 bg-muted/30">
          <TimelineSeeker
            duration={duration}
            currentTime={currentTime}
            onSeek={setCurrentTime}
            onPlayPause={() => setIsPlaying(!isPlaying)}
            isPlaying={isPlaying}
            bookmarks={bookmarks}
            onAddBookmark={handleAddBookmark}
            onUpdateBookmark={handleUpdateBookmark}
          />
        </div>

        {/* Summary and Activity Section - Capped Height with Scroll */}
        <div className="p-6 max-h-[320px] overflow-y-auto custom-scrollbar group/summary">
          {showActivityInput && (
            <div className="mb-6 p-4 bg-accent rounded-lg flex items-center gap-3">
              <input
                type="text"
                value={activityText}
                onChange={(e) => setActivityText(e.target.value)}
                placeholder="Log current status..."
                className="flex-1 min-h-[44px] px-4 py-2 bg-card rounded-md border border-border focus:outline-none text-sm"
              />
              <button
                onClick={handleRecordActivity}
                className="px-4 py-2 bg-foreground text-white rounded-md text-sm font-medium"
              >
                Save
              </button>
            </div>
          )}

          <div className="flex items-start justify-between mb-4">
            <div>
              <h4 className="text-foreground text-sm font-semibold mb-1">AI Event Summary</h4>
              <p className="text-muted-foreground text-xs">
                Generated from the last hour of autonomous surveillance
              </p>
            </div>
            <button
              onClick={handleCopySummary}
              className="flex items-center gap-2 px-3 py-1.5 rounded-md border border-border hover:bg-accent transition-colors text-xs font-medium text-foreground"
            >
              {summaryCopied ? <Check className="w-3.5 h-3.5" /> : <Copy className="w-3.5 h-3.5" />}
              {summaryCopied ? 'Copied' : 'Copy'}
            </button>
          </div>

          <p className="text-foreground text-sm leading-relaxed mb-6">
            Asset operating in idle state for 1 hour 4 minutes. No critical safety events detected. Two routine maintenance checks completed. Equipment showed normal operational parameters throughout monitoring period. Operator remained in cabin during entire session.
          </p>

          <div className="space-y-2">
            <h5 className="text-[10px] font-bold text-muted-foreground uppercase tracking-wider mb-2">Key Events</h5>
            {bookmarks.map((bookmark) => (
              <div key={bookmark.id} className="flex items-center gap-3 py-1 text-sm group cursor-pointer" onClick={() => setCurrentTime(bookmark.time)}>
                <span className="text-muted-foreground tabular-nums w-10 text-xs">{formatTime(bookmark.time)}</span>
                <span className="text-foreground group-hover:underline">{bookmark.label || 'Timestamp Marked'}</span>
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}
