import { Video, FileText, CheckCircle2, AlertTriangle, MoreVertical, Copy, Check, Target, History } from 'lucide-react';
import { useState } from 'react';
import { SafetyEventsFeed } from './SafetyEventsFeed';
import { MaintenanceAlerts } from './MaintenanceAlerts';
import { UnifiedMapView } from './UnifiedMapView';
import { TimelineSeeker } from './TimelineSeeker';

interface PreShiftReviewProps {
  videoRef?: React.RefObject<HTMLDivElement | null>;
  assetName: string;
  assetLocation: {
    lat: number;
    lng: number;
    siteName: string;
  };
}

export function PreShiftReview({ videoRef, assetName, assetLocation }: PreShiftReviewProps) {
  const [summaryCopied, setSummaryCopied] = useState(false);
  const [isPlaying, setIsPlaying] = useState(false);
  const [currentTime, setCurrentTime] = useState(3600);
  const [duration] = useState(7200);

  const handleCopySummary = async () => {
    const summaryText = `Safety Intelligence Summary - ${assetName}\n\nOperation across Zone B-2 shows moderate production pressure correlation. One near-miss event detected involving a personnel proximity incursion. Asset remained within designated safety zones for 94% of the shift. Recommended safety briefing for the next crew regarding Zone B-2 speed limits.\n\nGenerated by Safety Intelligence AI at ${new Date().toLocaleString()}`;
    await navigator.clipboard.writeText(summaryText);
    setSummaryCopied(true);
    setTimeout(() => setSummaryCopied(false), 2000);
  };

  const keySafetyEvents = [
    { time: '08:42', label: 'Personnel Incursion: Zone B-2 (Moderate)', type: 'warning', seconds: 522 },
    { time: '10:15', label: 'Production Velocity Warning: Section A', type: 'info', seconds: 1530 },
    { time: '14:30', label: 'Geofence Boundary Calibration Completed', type: 'success', seconds: 3600 },
    { time: '16:05', label: 'Proximity Sensor Auto-Test: Passed', type: 'success', seconds: 5400 },
  ];

  const timelineBookmarks = keySafetyEvents.map(event => ({
    id: event.time,
    time: event.seconds,
    label: event.label,
    tags: [event.type]
  }));

  const videoReports = [
    {
      id: '1',
      title: 'Daily Safety Recap - March 16, 2026',
      duration: '4:32',
      events: 12,
      thumbnail: 'daily',
    },
    {
      id: '2',
      title: 'Weekly Performance Summary',
      duration: '12:45',
      events: 47,
      thumbnail: 'weekly',
    },
    {
      id: '3',
      title: 'Monthly Trends Analysis',
      duration: '18:20',
      events: 186,
      thumbnail: 'monthly',
    },
  ];

  const actionItems = [
    { id: '1', text: 'Review proximity alert patterns in Zone C', priority: 'high', status: 'pending' },
    { id: '2', text: 'Schedule operator safety refresher training', priority: 'medium', status: 'pending' },
    { id: '3', text: 'Update geo-fence boundaries for expansion area', priority: 'low', status: 'completed' },
    { id: '4', text: 'Conduct equipment maintenance review', priority: 'high', status: 'pending' },
  ];

  return (
    <div className="bg-card rounded-[var(--radius-card)] border-2 border-border overflow-hidden shadow-[var(--elevation-sm)] mt-12 bg-gradient-to-b from-card/30 to-background/50">
      {/* Module Header - Standardized Layout */}
      <div className="px-6 py-4 bg-muted border-b border-border flex items-center justify-between">
        <div className="flex items-center gap-3">
          <CheckCircle2 className="w-5 h-5 text-foreground" />
          <h3 className="text-foreground">Shift Handover & Pre-Shift Review</h3>
        </div>
        <div className="flex items-center gap-2">
            <span className="text-muted-foreground font-[family-name:var(--font-family)]" style={{ fontSize: 'var(--text-sm)' }}>
              Last Update: {new Date().toLocaleTimeString()}
            </span>
        </div>
      </div>

      <div className="p-8 space-y-12 w-full">


        {/* Row 3: Handover Tasks */}
        <div className="bg-card rounded-[var(--radius-card)] border-2 border-border overflow-hidden shadow-[var(--elevation-sm)]">
          <div className="px-6 py-4 bg-muted border-b border-border flex items-center justify-between">
            <div className="flex items-center gap-3">
              <FileText className="w-5 h-5 text-foreground" />
              <h3 className="text-foreground">Tasks</h3>
            </div>
            <span className="text-muted-foreground font-[family-name:var(--font-family)]" style={{ fontSize: 'var(--text-xs)' }}>
              4 PENDING
            </span>
          </div>

          <div className="p-6 space-y-4">
            {/* Embedded Maintenance Alerts */}
            <div className="mb-8">
              <MaintenanceAlerts />
            </div>

            <div className="space-y-4">
              {actionItems.map((item) => (
                <div
                  key={item.id}
                  className={`
                    p-6 rounded-[var(--radius-card)] border-2 flex items-start gap-6 transition-colors
                    ${item.status === 'completed' ? 'bg-muted/30 border-border opacity-70' : 'bg-background border-border hover:border-foreground/30'}
                  `}
                >
                  <button
                    className="min-w-[64px] min-h-[64px] flex items-center justify-center rounded-[var(--radius-button)] border-2 border-border hover:bg-muted transition-colors flex-shrink-0"
                  >
                    {item.status === 'completed' ? (
                      <CheckCircle2 className="w-8 h-8 text-foreground" />
                    ) : (
                      <div className="w-8 h-8 rounded-full border-2 border-border hover:border-foreground"></div>
                    )}
                  </button>

                  <div className="flex-1 pt-2">
                    <div className="flex items-center justify-between mb-2">
                      <p className={`font-[family-name:var(--font-family)] ${item.status === 'completed' ? 'text-muted-foreground line-through' : 'text-foreground'}`} style={{ fontSize: 'var(--text-xl)' }}>
                        {item.text}
                      </p>
                      <div 
                        className={`
                          px-4 py-1.5 rounded-full font-[family-name:var(--font-family)] font-[var(--font-weight-medium)]
                          ${item.priority === 'high' ? 'bg-foreground text-white' : ''}
                          ${item.priority === 'medium' ? 'bg-muted-foreground text-white' : ''}
                          ${item.priority === 'low' ? 'bg-border text-foreground' : ''}
                        `}
                        style={{ fontSize: 'var(--text-xs)' }}
                      >
                        {item.priority.toUpperCase()}
                      </div>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
